force-app/main/default/objects/Case/fields/SLA_Deadline__c.field-meta.xml
<CustomField>
    <fullName>SLA_Deadline__c</fullName>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Routing_Rule__mdt/Case_Routing_Rule__mdt.object-meta.xml
<CustomObject>
    <description>It routes case to a specific user and assigns to a priority based on the source</description>
    <label>Case Routing Rule</label>
    <pluralLabel>Case Routing Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Routing_Rule__mdt/fields/Assigned_To_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_User__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Assigned To User</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Routing_Rule__mdt/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technical</fullName>
                <default>true</default>
                <label>Technical</label>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_SLA_Rule__mdt/Case_SLA_Rule__mdt.object-meta.xml
<CustomObject>
    <label>Case SLA Rule</label>
    <pluralLabel>Case SLA Rule</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_SLA_Rule__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_SLA_Rule__mdt/fields/SLA_Hours__c.field-meta.xml
<CustomField>
    <fullName>SLA_Hours__c</fullName>
    <label>SLA Hours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseRoutingHandler.cls
public with sharing class CaseRoutingHandler {
    public static void autoAssignAndSetSLA(List<Case> newCases) {

        //Fetch metadata records for lead assignment and SLA

        List<Case_Routing_Rule__mdt> rules = [SELECT Case_Type__c, Assigned_To_User__c FROM Case_Routing_Rule__mdt];
        List<Case_SLA_Rule__mdt> SLAs = [SELECT Priority__c, SLA_Hours__c FROM Case_SLA_Rule__mdt];

        //Create a Map of Case Type + Assignment and Metadata record

        Map<String, Case_Routing_Rule__mdt> routingMap = new Map<String, Case_Routing_Rule__mdt>(); 
        for(Case_Routing_Rule__mdt rule: rules) {

            //Extract the key
            String key = (String)rule.Case_Type__c;
           
            //Assign the metadata record
            routingMap.put(key, rule);
        }

        //Create a Map of Prioty  + SLA and Metadata record

        Map<String, Case_SLA_Rule__mdt> SLAMap = new Map<String, Case_SLA_Rule__mdt>(); 
        for(Case_SLA_Rule__mdt Sla: SLAs) {
            //Extract the key
            String key = (String)Sla.Priority__c;
           
            //Assign the metadata record
            SLAMap.put(key, Sla);
        }

        //Iterate through the cases and assign them based on the criteria defined in the metadata
        for(Case c: newCases) {
            if((c.Status == 'New') && c.Type != NULL && c.Priority != NULL) {
            
            String Casetype = c.Type;
            String Prioritytype = c.Priority;
            
            //If the key exists then the case can be assigned to the appropriate person 
            if(routingMap.containsKey(Casetype)) {
                Case_Routing_Rule__mdt rule = routingMap.get(Casetype);
                c.OwnerId = rule.Assigned_To_User__c;
            }
            //If the key exists then the SLA is populated according to  hours
            if(SLAMap.containsKey(Prioritytype)) {
                    Case_SLA_Rule__mdt sla = SLAMap.get(Prioritytype);
                    c.SLA_Deadline__c = System.now().addHours((Integer)sla.SLA_Hours__c);
                }
        
            
        }
        }  
}
}